exchange:
  NAME: binance
  API_KEY: asdfasdf
  API_SECRET: asdfasdfasdf
  MARKET: BTCUSDT
database:
  POSTGRES_DB: orderbook
  POSTGRES_USER: user
  POSTGRES_SERVER: localhost
  POSTGRES_PASSWORD: passwd