name: create github release

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[release] ')"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Build package
      run: |
        go build -v ./...
  
  test:
    needs: [build]
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[release] ')"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Test package
      run: |
        go test -v ./...

  release:
    needs: [test]
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[release] ')"
    steps:
      - uses: actions/checkout@master
      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            *.jar